# Generated by Django 5.2.1 on 2025-06-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='state_images/'),
        ),
    ]
