# Generated by Django 5.2.1 on 2025-06-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_state_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristplace',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='place',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='touristplace',
            name='best_time',
        ),
        migrations.RemoveField(
            model_name='touristplace',
            name='location_url',
        ),
        migrations.RemoveField(
            model_name='touristplace',
            name='main_image',
        ),
        migrations.AddField(
            model_name='touristplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='place_images/'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to='place_images/'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.touristplace'),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='PlaceCategory',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
