# Generated by Django 5.2.1 on 2025-06-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_touristplace_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='best_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='category',
            field=models.CharField(blank=True, choices=[('Religious', 'Religious'), ('Cultural', 'Cultural'), ('Spiritual', 'Spiritual'), ('Historical', 'Historical'), ('Natural', 'Natural'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='main_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
